---

- name: Provision cluster
  hosts: localhost
  tasks:
    - terraform:
        project_path: '{{ playbook_dir }}/terraform'
        state: present

- name: Deploy Spark
  hosts: spark
  # So we can wait for SSH.
  gather_facts: no
  become: yes
  roles:
    - spark
